name: void_quest
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.10.0
  google_mobile_ads: ^6.0.0
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icons.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/videos/
